# Generated by Django 3.2.8 on 2024-04-17 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hairo_Back', '0002_cours_fichierpdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images_cours/'),
        ),
        migrations.CreateModel(
            name='QCM_Globale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('json', models.JSONField()),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qcms_globale', to='Hairo_Back.cours')),
            ],
        ),
        migrations.CreateModel(
            name='QCM_by_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.JSONField()),
                ('score', models.IntegerField()),
                ('qcm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qcms_by_user', to='Hairo_Back.qcm_globale')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qcms_by_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
