# Generated by Django 3.2.8 on 2024-04-18 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hairo_Back', '0003_auto_20240417_1428'),
        ('Hairo_Back', '0003_auto_20240417_1957'),
    ]

    operations = [
    ]
