# Generated by Django 3.2.8 on 2024-04-18 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hairo_Back', '0004_merge_0003_auto_20240417_1428_0003_auto_20240417_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='qcm_by_user',
            name='qcm',
        ),
        migrations.RemoveField(
            model_name='qcm_by_user',
            name='user',
        ),
        migrations.RemoveField(
            model_name='qcm_globale',
            name='cours',
        ),
        migrations.RemoveField(
            model_name='question',
            name='qcm',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='question',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='user',
        ),
        migrations.RemoveField(
            model_name='qcm',
            name='description',
        ),
        migrations.RemoveField(
            model_name='qcm',
            name='titre',
        ),
        migrations.AddField(
            model_name='qcm',
            name='contenu_json',
            field=models.FileField(default='fichier_qcm/qcm.json', upload_to='qcms/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='QCM_by_user',
        ),
        migrations.DeleteModel(
            name='QCM_Globale',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='UserResponse',
        ),
        migrations.AddField(
            model_name='resultat',
            name='qcm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hairo_Back.qcm'),
        ),
        migrations.AddField(
            model_name='resultat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
