# Generated by Django 3.2.8 on 2024-05-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hairo_Back', '0005_auto_20240418_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichierpdf',
            name='date_revised',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichierpdf',
            name='is_revised',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_three_courses',
            field=models.ManyToManyField(blank=True, related_name='last_three_courses', to='Hairo_Back.Cours'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_three_qcm',
            field=models.ManyToManyField(blank=True, related_name='last_three_qcm', to='Hairo_Back.QCM'),
        ),
        migrations.AddField(
            model_name='user',
            name='student_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
