# Generated by Django 3.2.8 on 2024-06-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hairo_Back', '0006_auto_20240511_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichierpdf',
            name='date_revised',
        ),
        migrations.RemoveField(
            model_name='fichierpdf',
            name='is_revised',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_three_courses',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_three_qcm',
        ),
        migrations.RemoveField(
            model_name='user',
            name='student_number',
        ),
        migrations.AddField(
            model_name='user',
            name='faculte',
            field=models.CharField(default='non rensigné', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='moyenne_visee',
            field=models.CharField(default='non rensigné', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='prenom',
            field=models.CharField(default='non renseigne', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='tutorat',
            field=models.CharField(default='non rensigné', max_length=255),
        ),
    ]
