# Generated by Django 3.2.8 on 2024-06-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hairo_Back', '0007_auto_20240629_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='non rensigné', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='prenom',
            field=models.CharField(default='non rensigné', max_length=255),
        ),
    ]
